[package]
name = "jc_custom_platform_tauri"
version = "0.1.0"
description = "自定义开发平台"
authors = ["JC"]
edition = "2021"

[lib]
name = "jc_custom_platform_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
calamine = "0.26"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
thiserror = "2"
